require.config({
    paths:{
        'banner':'./app/js/Carousel',
        'home':'./app/js/home',
        'scroll':'./app/js/scroll',
        'show':'./app/js/show',
        'render':'./app/js/render',
        'jquery':'./app/libs/jquery.min'
    }
})