require.config({
    paths:{
        'Mock':'./app/libs/mock-min',
        'creatMock':'./app/js/creatMock',
        'jquery':'./app/libs/jquery.min',
        'index':'./app/js/index',
        'getMock':'./app/js/getMock',
        'render':'./app/js/render',
        'alert':'./app/js/alert'
    }
})