require.config({
    paths:{
        'Swiper':'./app/libs/swiper.min',
        'css':'./app/libs/css.min',
        'index':'./app/js/index'
    },
    shim:{
        'Swiper':{
            exports:[],
            deps:['css!../src/app/libs/swiper.min.css']
        },
        'index':{
            exports:[],
            deps:['css!../src/app/css/index.css']
        }
    }
})